spring:
  cloud:
    #ribbon重试机制
    loadbalancer:
      retry:
        enabled: true

ribbon:
  ReadTimeout: 27000
  ConnectTimeout: 2000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 1
  okToRetryOnAllOperations: true

#hystrix 取消超时
hystrix:
  threadpool:
    default:
      coreSize: 100
  command:
    circuitBreaker:
      requestVolumeThreshold: 1000
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            #2分钟熔断 (ReadTimeout+ConnectTimeout) * (1 + MaxAutoRetries) * (1 + MaxAutoRetriesNextServer)
            timeoutInMilliseconds: 120000

