# application文件是springboot自动导入的情况
# spring boot会自动扫描其中的内容并根据自动配置的设置来改变springboot 的自动配置默认值

# yml以数据为重新更适合做配置文件
server:
  port: 8081
#  以数据缩进来控制层级关系 只要是左对齐一列数据 都是同一层级
# 普通的值有 "" 和 '' 两种区分 其中 "" 不会转义字符串中的字符 如 \n \t 等等 单引号会转义字符
amd: yes
intel: 'AMD\nYes'
nvidia: "AMD\nYes"
# 对象、map（键值对）直接声明
# 多行写法
friends:
  name: name
  age: 2
# 单行写法
people: {name: name,age: 20}
# 数组 list、set写法
pets:
  - cat
  - dog
  - pig

animal: [cat,dog,pig]

#-------------------------------------------------------------------------
#设定指定对象中的所有属性
assign:
  name: name
  name2: name2
  age: 30
  speak: 'AMD\nYes'
  idea: "AMD\nYes"
  pets:
    - cat
    - dog
    - pig
  friends:
    name: name
    age: 2
  say: say
# 和之前的注释没有区别，根据空格变成.缩进
base.name: asdass